### ISSUE TITLE
"pydeps -o some/file.svg other/file.py" fails

### ISSUE THREAD

**Issue by zachwelch** [thebjorn/pydeps#10]
Since pydeps does a ``chdir`` to the directory containing the source file, any relative path passed to -o will fail to open. One solution would be to call ``abspath`` on the ``output`` variable before the ``chdir``.

**Comment by thebjorn** [comment]
Hi @zachwelch and thank you for the problem reports.

**Comment by thebjorn** [comment]
The following call is ok:

`(dev) go|c:\github\pydeps> pydeps -o build\pydeps-issue4.svg pydeps`

and this fails:
```
(dev) go|c:\github\pydeps> pydeps -o build\pydeps-issue4.svg pydeps\depgraph.py
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\srv\venv\dev\Scripts\pydeps.exe\__main__.py", line 9, in <module>
  File "c:\srv\venv\dev\lib\site-packages\pydeps\pydeps.py", line 246, in pydeps
    _pydeps(**_args)
  File "c:\srv\venv\dev\lib\site-packages\pydeps\pydeps.py", line 33, in _pydeps
    g = py2dep(fname, **kw)
  File "c:\srv\venv\dev\lib\site-packages\pydeps\py2depgraph.py", line 348, in py2dep
    return depgraph.DepGraph(mf_depgraph, mf._types, **kw)
  File "c:\srv\venv\dev\lib\site-packages\pydeps\depgraph.py", line 272, in __init__
    self.calculate_bacon()
  File "c:\srv\venv\dev\lib\site-packages\pydeps\depgraph.py", line 377, in calculate_bacon
    bacon(self.sources['__main__'], 0)
KeyError: '__main__'
```

`pydeps` likes to handle entire packages instead of individual files (which is my personal use-case most of the time), but this is either 

1. an excessively unhelpful error message, or
2. a bug: `pydeps` should handle individual files.

**Comment by thebjorn** [comment]
The above is completely wrong ;-)  The original analysis is correct.
