### ISSUE TITLE
Failed on py.py

### ISSUE THREAD

**Issue by joshkel** [thebjorn/pydeps#12]
[html5lib](https://github.com/html5lib/html5lib-python) has a file called `html5lib/trie/py.py`, so the full module reference is `html5lib._trie.py`. If I run pydeps on this or on a project that uses this, it fails with an error similar to the following:

```
Traceback (most recent call last):
  File "C:\src\html5lib-python\env\Scripts\pydeps-script.py", line 11, in <module>
    load_entry_point('pydeps==1.5.1', 'console_scripts', 'pydeps')()
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\pydeps.py", line 263, in pydeps
    _pydeps(**_args)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\pydeps.py", line 38, in _pydeps
    g = py2dep(fname, **kw)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\py2depgraph.py", line 351, in py2dep
    return depgraph.DepGraph(mf_depgraph, mf._types, **kw)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\depgraph.py", line 275, in __init__
    self.calculate_bacon()
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\depgraph.py", line 385, in calculate_bacon
    bacon(self.sources['__main__'], 0)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\depgraph.py", line 382, in bacon
    bacon(self.sources[imp], n + 1)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\depgraph.py", line 382, in bacon
    bacon(self.sources[imp], n + 1)
  File "c:\src\html5lib-python\env\lib\site-packages\pydeps\depgraph.py", line 382, in bacon
    bacon(self.sources[imp], n + 1)
  [Previous line repeated 2 more times]
KeyError: 'html5lib._trie.py'
```

I believe that the problem is [this line](https://github.com/thebjorn/pydeps/blob/cf1794338f2903dd7448b9b9a292cd12ebe5870f/pydeps/depgraph.py#L243) and [this line](https://github.com/thebjorn/pydeps/blob/cf1794338f2903dd7448b9b9a292cd12ebe5870f/pydeps/depgraph.py#L247) within depgraph.py. The names (`depgraph` keys) at this point are module names (e.g., `html5lib._trie.py`), not file paths (e.g., `html5lib/_trie/py.py`), so removing `.py` isn't necessary, and it breaks processing of this module.

Therefore, I think the fix is to update depgraph.py to not remove `.py` from names. However, I could be missing something. Does this sound right to you? If so, I can submit a PR.

Thanks!

**Comment by thebjorn** [comment]
Hi @joshkel and thanks for the problem report (I've been on summer vacation so apologies for the late reply).  Your analysis seems probable (and there is a bit of fuzziness in the code when it comes to module paths and file paths).

I love receiving PRs :-)
(please add a test case that fails before and passes after your PR).
