### ISSUE TITLE
Resolving relative dependencies?

### ISSUE THREAD

**Issue by JohnPeng47** [thebjorn/pydeps#200]
Does Pydeps not resolve relative dependencies? (Aside: _are relative dependencies considered malpractise in python_?)

Following command:
`python -m pydeps --show-deps --debug route.py`

Does not show any of the relative dependencies imported like so
`
from .schema import CreateGraphReq, ...
from .service import GraphManager, ....
`

Cheers (also thanks for making this, especially looking forward to using the intermediate output for a project I'm working on for writing automatic test cases)

**Comment by thebjorn** [comment]
> Does Pydeps not resolve relative dependencies?

It should (there are tests: https://github.com/thebjorn/pydeps/blob/master/tests/test_relative_imports.py). If you have a testcase I can look into it.

> Aside: are relative dependencies considered malpractise in python?

Relative imports are kosher in Python.

**Comment by JohnPeng47** [comment]
Hey thanks for the quick response, in the middle of restructuring my Python dir layout, was using really weird pathing with potentially some circular dependencies along the way, will rerun pydeps after and let you know

**Comment by JohnPeng47** [comment]
Here, I ran my command from the root of this directory:
`python -m pydeps --show-deps --max-module-depth 2 src\server\routes\graph\route.py`

Here is the file:
https://github.com/JohnPeng47/KongMono/blob/master/KongServer/src/server/routes/graph/route.py

Here is generated deps file:
`
{
    "fastapi": {
        "bacon": 1,
        "imported_by": [
            "fastapi.applications",
            "fastapi.param_functions",
            "fastapi.routing",
            "route.py"
        ],
        "imports": [
            "fastapi.applications",
            "fastapi.background",
            "fastapi.datastructures",
            "fastapi.exceptions",
`

The generated deps file only shows fastapi and networkx, but it misses both my relative imports and the src.KongBot imports

**Comment by itaowei** [comment]
I also have the similar problem and one test case for that issue is [this file](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/backends/backend_qt5.py) under the repository [matplotlib](https://github.com/matplotlib/matplotlib).

The error message is shown below
```bash
Traceback (most recent call last):
  File "/$WORKDIR/AgileAgent/process.py", line 72, in <module>
    manager = Manager(f"/$WORKDIR/virtual_env/manager/{repo_full_name}/new_require.txt", \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$WORKDIR/AgileAgent/manager.py", line 53, in __init__
    file_deps_dict = analyze_file_dep(self.candidate_file_path_list, cache_dir="cache")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$WORKDIR/AgileAgent/static_analyzer.py", line 22, in analyze_file_dep
    file_deps_dict[file_path] = py2depgraph.py2dep(target_file, exclude_exact=package_exclude_list, include_missing=False, show_cycles = False,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/site-packages/pydeps/py2depgraph.py", line 237, in py2dep
    mf.run_script(dummy.fname)
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/site-packages/pydeps/py2depgraph.py", line 122, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/site-packages/pydeps/py2depgraph.py", line 159, in load_module
    module = mf27.ModuleFinder.load_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/site-packages/pydeps/mf27.py", line 153, in load_module
    self.scan_code(co, m)
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/site-packages/pydeps/mf27.py", line 206, in scan_code
    parent = self.determine_parent(m, level=level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/$HOME/anaconda3/envs/AgileAgent/lib/python3.11/modulefinder.py", line 188, in determine_parent
    raise ImportError("relative importpath too deep")
ImportError: relative importpath too deep
```

**Comment by thebjorn** [comment]
@itaowei interesting. The error is coming from Python's modulefinder module, and indeed if you run in directly you'll see the same result: 
```
(pydeps200) go|C:\srv\venv\pydeps200\Lib\site-packages> python -m modulefinder matplotlib\__init__.py
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 664, in <module>
    mf = test()
         ^^^^^^
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 657, in test
    mf.run_script(script)
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 153, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 349, in load_module
    self.scan_code(co, m)
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 436, in scan_code
    parent = self.determine_parent(m, level=level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\modulefinder.py", line 188, in determine_parent
    raise ImportError("relative importpath too deep")
ImportError: relative importpath too deep
```

**Comment by ZiqianXu** [comment]
Hey @thebjorn, were you able to root cause the issue? I'm having similar issue with relative path import via `from . import <moduleName>`.
It's for a simple OSS module [grpc python file _server.py](https://github.com/grpc/grpc/blob/10a95e03d97ff694f7d41455047caf601920342d/src/python/grpcio/grpc/aio/_server.py)
```
python3 -m pydeps grpc/aio/_server.py --show-deps --pylib --no-output --noshow --include-missing
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/__main__.py", line 2, in <module>
    pydeps()
  File "/usr/local/lib/python3.8/dist-packages/pydeps/pydeps.py", line 175, in pydeps
    return _pydeps(inp, **_args)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/pydeps.py", line 39, in _pydeps
    dep_graph = py2depgraph.py2dep(trgt, **kw)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/py2depgraph.py", line 237, in py2dep
    mf.run_script(dummy.fname)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/py2depgraph.py", line 122, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/py2depgraph.py", line 159, in load_module
    module = mf27.ModuleFinder.load_module(
  File "/usr/local/lib/python3.8/dist-packages/pydeps/mf27.py", line 153, in load_module
    self.scan_code(co, m)
  File "/usr/local/lib/python3.8/dist-packages/pydeps/mf27.py", line 206, in scan_code
    parent = self.determine_parent(m, level=level)
  File "/usr/lib/python3.8/modulefinder.py", line 198, in determine_parent
    raise ImportError("relative importpath too deep")
ImportError: relative importpath too deep
```
Checking my python3.8 source path directory, all file with `from . import <moduleName>` returns the same type of error from pydeps.

Thanks for your help on debugging this!
