### ISSUE TITLE
use of `--externals` results in TypeError: 'Config' object does not support item assignment

### ISSUE THREAD

**Issue by bhpayne** [thebjorn/pydeps#206]
I just discovered this software and am grateful that it exists. 

I tried using `--externals` but encountered an error:
```bash
pydeps --externals --noshow load_time.py 
Traceback (most recent call last):
  File "/usr/local/bin/pydeps", line 8, in <module>
    sys.exit(pydeps())
  File "/usr/local/lib/python3.9/site-packages/pydeps/pydeps.py", line 149, in pydeps
    _args['curdir'] = os.getcwd()
TypeError: 'Config' object does not support item assignment
```

I don't see a reason why that line <https://github.com/thebjorn/pydeps/blob/master/pydeps/pydeps.py#L149>
is sensitive to that flag.

Not including `--externals` does work,
```bash
pydeps --noshow load_time.py 
```

I'm running
```bash
python3 --version
Python 3.9.18
pydeps --version
pydeps v1.12.17
```

The script that I'm using `pydeps` to analyze is
```bash
cat load_time.py 
import time
```

**Comment by thebjorn** [comment]
Hi @bhpayne and thank you for your interest in pydeps. This bug is fixed in v.1.12.18 available on PyPI now.
