### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by webe3** [thebjorn/pydeps#3]
I get an AttributeError when I run pydeps.

$ pydeps --externals cv_prioritizer_wrapper.py
Traceback (most recent call last):
  File "/usr/local/bin/pydeps", line 11, in <module>
    sys.exit(pydeps())
  File "/usr/local/lib/python2.7/dist-packages/pydeps/pydeps.py", line 226, in pydeps
    exts = externals(fname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/pydeps.py", line 197, in externals
    depgraph = py2dep(pkgname, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 302, in py2dep
    mf.run_script(fname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 116, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 129, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 188, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 129, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 195, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 292, in load_module
    module = self.load_package(fqname, pathname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 481, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 341, in _safe_import_hook
    self.import_hook(name, caller, [sub], level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line 137, in import_hook
    self.ensure_fromlist(m, fromlist)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 173, in ensure_fromlist
    self._add_import(getattr(module, sub))
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py", line 123, in _add_import
    if module.__file__ or self.include_pylib_all:
AttributeError: 'str' object has no attribute '__file__'

**Comment by thebjorn** [comment]
Which version of pydeps (`pydeps --version`), python (`python -V`), and OS (e.g. `uname -a`)?  Do you have a self-contained sample that demonstrates the problem?

I generally don't use pydeps on single files since you can just look at the top of the file for the imports. If you have a directory structure similar to:

    parent_dir/__init__.py
    parent_dir/proj_dir/cv_prioritizer_wrapper.py

could you try running:

    parent_dir$ pydeps --externals proj_dir

**Comment by webe3** [comment]
On Mon, 2017-03-06 at 16:33 -0800, Bjorn wrote:
> Which version of pydeps (pydeps --version), python (python -V), and
> OS (e.g. uname -a)? Do you have a self-contained sample that
> demonstrates the problem?
> I generally don't use pydeps on single files since you can just look
> at the top of the file for the imports. If you have a directory
> structure similar to:
> parent_dir/__init__.py
> parent_dir/proj_dir/cv_prioritizer_wrapper.py
> could you try running:
> parent_dir$ pydeps --externals proj_dir
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

$ pydeps --version
pydeps v1.3.5

$ python -V
Python 2.7.13

I am running on Debian testing/stretch
$ uname -a
Linux brente 4.9.2.170124 #1 SMP PREEMPT Tue Jan 24 16:51:35 CST 2017
x86_64 GNU/Linux


$ pydeps --externals cv_prioritizer
Traceback (most recent call last):
  File "/usr/local/bin/pydeps", line 11, in <module>
    sys.exit(pydeps())
  File "/usr/local/lib/python2.7/dist-packages/pydeps/pydeps.py", line
226, in pydeps
    exts = externals(fname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/pydeps.py", line
197, in externals
    depgraph = py2dep(pkgname, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 302, in py2dep
    mf.run_script(fname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
116, in run_script
    self.load_module('__main__', fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist,
level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname,
parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist,
level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname,
parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist,
level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
129, in import_hook
    q, tail = self.find_head_package(parent, name)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
195, in find_head_package
    q = self.import_module(head, qname, parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname,
parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
292, in load_module
    module = self.load_package(fqname, pathname)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
481, in load_package
    self.load_module(fqname, fp, buf, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
329, in _safe_import_hook
    self.import_hook(name, caller, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist,
level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
131, in import_hook
    m = self.load_tail(q, tail)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
210, in load_tail
    m = self.import_module(head, mname, m)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 137, in import_module
    module = mf27.ModuleFinder.import_module(self, partnam, fqname,
parent)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
280, in import_module
    m = self.load_module(fqname, fp, pathname, stuff)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 144, in load_module
    self, fqname, fp, pathname, (suffix, mode, kind)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
311, in load_module
    self.scan_code(co, module)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
427, in scan_code
    self._safe_import_hook(name, module, fromlist, level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
341, in _safe_import_hook
    self.import_hook(name, caller, [sub], level=level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 115, in import_hook
    return mf27.ModuleFinder.import_hook(self, name, caller, fromlist,
level)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/mf27.py", line
137, in import_hook
    self.ensure_fromlist(m, fromlist)
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 173, in ensure_fromlist
    self._add_import(getattr(module, sub))
  File "/usr/local/lib/python2.7/dist-packages/pydeps/py2depgraph.py",
line 123, in _add_import
    if module.__file__ or self.include_pylib_all:
AttributeError: 'str' object has no attribute '__file__'

**Comment by thebjorn** [comment]
I think I've fixed this problem now.  Get version 1.3.6 from PyPi.  Reopen this issue if you're still having problems.
